### ISSUE TITLE
Clearing action does not work

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-payment-test-ui#2]
Steps to reproduce:

1. Start Kill Bill
2. Open Kaui home page
3. Click on the plug icon -> Payment Test
4. Select "Configure Pending" In the "Set Status" drop-down - This works as expected
5. Select "Clear All Status " In the "Set Status" drop-down - This displays the "We're sorry, but something went wrong." message.

The following error is seen in the log file:

```
Caused by: java.lang.IllegalArgumentException: No enum constant org.killbill.billing.plugin.payment.TestingStates.Actions.ACTION_RESET
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.killbill.billing.plugin.payment.TestingStates$Actions.valueOf(TestingStates.java:37)
	at org.killbill.billing.plugin.payment.resources.PaymentTestResource.configure(PaymentTestResource.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jooby.internal.mvc.MvcHandler.lambda$invoke$0(MvcHandler.java:278)
	at org.jooby.funzy.Throwing.fn(Throwing.java:2423)
	at org.jooby.funzy.Throwing.access$400(Throwing.java:39)
	at org.jooby.funzy.Throwing$Supplier.get(Throwing.java:145)
	at org.jooby.funzy.Try.apply(Try.java:691)
	at org.jooby.internal.mvc.MvcHandler.invoke(MvcHandler.java:269)
	at org.jooby.internal.mvc.MvcHandler.handle(MvcHandler.java:251)
	at org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at org.jooby.Route$Chain.next(Route.java:2164)
	at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)
	... 97 common frames omitted
```

I believe the code needs to be fixed [here](https://github.com/killbill/killbill-payment-test-ui/blob/6ed5c3623c66e9ecf9f4a03c34a69cefbd3f4bd4/lib/payment_test/client.rb#L42) (`ACTION_CLEAR` needs to be specified instead of `ACTION_RESET`) but to be confirmed.

**Comment by tungleduyxyz** [comment]
Hi @reshmabidikar, you're right, there was a mistake with the action name. I made a pull request to fix this issue here: https://github.com/killbill/killbill-payment-test-ui/pull/5

**Comment by reshmabidikar** [comment]
Tested this locally and this works as expected.
